name: Bug Report
description: Report an issue, bug, or defect
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A short description of the bug or issue
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Outline the steps someone can follow in order to reproduce the issue or bug
      value: |
        1. Go to...
        2. Click on...
        3. Wait for...
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: Describe what happened after performing the steps listed in the *Reproduction Steps*
      value: |
        I'd expect the page to reload without any error messages being displayed.
    validations:
      required: true

  - type: textarea
    id: actual-outcome
    attributes:
      label: Actual Outcome
      description: Describe what actually happened after performing the steps listed in the *Reproduction Steps*
      value: |
        An error message is displayed on screen: `[22-Jan-2024 01:02:03 UTC] PHP Notice:  Only variables should be passed by reference in /srv/public/html/index.php on line 456`
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System and Environment Information
      description: The following information will aid in reproduction of the issue
      value: |
        PHP Version:
        WordPress Version:
        Browser:
        Operating System:

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional information such as error logs, screenshots, screen recordings, or any other details relevant to the issue

  - type: input
    id: helpdesk-link
    attributes:
      label: Help Desk Ticket Link
      description: If this issue is related to a customer support request, please provide a link to the ticket

