name: Sync Issue Bug Report Organization File

on:
  push:
    paths:
      # Templates.
      - .github/templates/issue/bug-report.yml

      # Defs.
      - defs/teams-config.yml

      # When this file is edited.
      - .github/workflows/workflow-issue-bug-sync.yml
    branches:
      - main
  workflow_dispatch:

env:
  ORGANIZATION: ${{ github.repository_owner }}

jobs:
  projects:
    name: PHPCS Workflow Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync phpcs
        uses: ./.github/actions/files-sync
        with:
          org: ${{ env.ORGANIZATION }}
          secrets: ${{ toJson(secrets) }}
          what: issue/bug-report.yml
